class Constants:
    class FINANCIALS:
        INCOME_STATEMENT = "income_statement"
        BALANCE_SHEET = "balance_sheet"
        CASH_FLOW_STATEMENT = "cash_flow_statement"

    class BALANCE_SHEET:
        DATE = "date"
        REVENUE = "Revenue"
        REVENUE_GROWTH = "Revenue Growth"
        COST_OF_REVENUE = "Cost of Revenue"
        GROSS_PROFIT = "Gross Profit"
        R&D_EXPENSES = "R&D Expenses"
        SG&A_EXPENSE = "SG&A Expense"
        OPERATING_EXPENSES = "Operating Expenses"
        OPERATING_INCOME = "Operating Income"
        INTEREST_EXPENSE = "Interest Expense"
        EARNINGS_BEFORE_TAX = "Earnings before Tax"
        INCOME_TAX_EXPENSE = "Income Tax Expense"
        NET_INCOME_NON_CONTROLLING_INT = "Net Income - Non-Controlling int"
        NET_INCOME_DISCONTINUED_OPS = "Net Income - Discontinued ops"
        NET_INCOME = "Net Income"
        PREFERRED_DIVIDENDS = "Preferred Dividends"
        NET_INCOME_COM = "Net Income Com"
        EPS = "EPS"
        EPS_DILUTED = "EPS Diluted"
        WEIGHTED_AVERAGE_SHS_OUT = "Weighted Average Shs Out"
        WEIGHTED_AVERAGE_SHS_OUT_DIL = "Weighted Average Shs Out (Dil)"
        DIVIDEND_PER_SHARE = "Dividend per Share"
        GROSS_MARGIN = "Gross Margin"
        EBITDA_MARGIN = "EBITDA Margin"
        EBIT_MARGIN = "EBIT Margin"
        PROFIT_MARGIN = "Profit Margin"
        FREE_CASH_FLOW_MARGIN = "Free Cash Flow margin"
        EBITDA = "EBITDA"
        EBIT = "EBIT"
        CONSOLIDATED_INCOME = "Consolidated Income"
        EARNINGS_BEFORE_TAX_MARGIN = "Earnings Before Tax Margin"
        NET_PROFIT_MARGIN = "Net Profit Margin"

    class CASH_FLOW_STATEMENT:
        DATE = "date"
        DEPRECIATION_AND_AMORTIZATION = "Depreciation & Amortization"
        STOCK_BASED_COMPENSATION = "Stock-based compensation"
        OPERATING_CASH_FLOW = "Operating Cash Flow"
        CAPITAL_EXPENDITURE = "Capital Expenditure"
        ACQUISITIONS_AND_DISPOSALS = "Acquisitions and disposals"
        INVESTMENT_PURCHASES_AND_SALES = "Investment purchases and sales"
        INVESTING_CASH_FLOW = "Investing Cash flow"
        ISSUANCE_REPAYMENT_OF_DEBT = "Issuance (repayment) of debt"
        ISSUANCE_BUYBACKS_OF_SHARES = "Issuance (buybacks) of shares"
        DIVIDENT_PAYMENTS = "Dividend payments"
        FINANCING_CASH_FLOW = "Financing Cash Flow"
        EFFECT_OF_FOREXT_CHANGES_ON_CASH = "Effect of forex changes on cash"
        NET_CASH_FLOW_CHANGE_IN_CASH = "Net cash flow / Change in cash"
        FREE_CASH_FLOW = "Free Cash Flow"
        NET_CASH_MARKET_CAP = "Net Cash/Marketcap"